import React from 'react'
import './reviewsBody.css';

const ReviewsBody = () => {
  return (
    <div className='mydearest__reviewsbody'>
        ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody ReviewsBody
    </div>
  )
}

export default ReviewsBody